--[[
    Generated By The DV7(s) & The Running Man Team!
]]--

dv7 = {}
rma = {}

local lIllIlIlIllIlIlIllIlI = function()
    local x = 8
end

while true do 
    local input = io.read()
    if input ~= 'y' then
        if input == 'n' then
            print('Killing Bytecode process')
            break
        else
            print("The system should write y/n (yes/no)")
        end
    else
        print("Ngh.. I clapped the server")
    end
end

if dv7.kurwa == rma.isClient then 
    print("Server restore..")
else
    print("Server shut down")
end

local y

if rma.kuruba then 
    y = 'b3s3S^&fXBFEFR^7bX#R^F'
    print(y)
else
    print("Could not output: " .. y .. "\nSad Life")
end

kuruba = {}

function kuruba.getKurub4()
    while kuruba.youDrinkingCoconut do
        local q = io.read()
        if q ~= 'clapping cheeks' then
            if q == 'clapping dix' then
                print("You're Gay")
                break
            else
                print("You're Yappington")
                kuruba.kiss(false)
            end
        end
    end
end
